version: "3.1"
name: testovoe
services:
  postgres:
    image: mirror.gcr.io/postgres:14
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: katalog
      POSTGRES_PASSWORD: admin
    #   PGDATA: /var/lib/postgresql/data/pgdata
    # volumes:
    #   - ./volumes/postgres:/var/lib/postgresql/data/pgdata
    #   - ./postgres/migrations:/docker-entrypoint-initdb.d