version: "3.1"
name: testovoe
services:
  postgres:
    image: mirror.gcr.io/postgres:14
    networks:
      service_network:
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: katalog
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres/migrations:/docker-entrypoint-initdb.d
  
  service:
    networks:
      service_network:
    build: .
    ports:
      - "5000:5000"
  
networks:
  service_network:
    driver: bridge